name: Deploy to Page Branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        run: pnpm build

      - name: Deploy to Page Branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -B page
          git rm -rf .
          mv dist/* .
          echo "tcilay.fun" > CNAME
          git add .
          git commit -m "Deploy to Page Branch"
          git push -f origin page
